### ISSUE TITLE
Mr. ME! doesnt let Tarnished Keeper steal shop items

### ISSUE THREAD

**Issue by Feutor** [OpenSauce04/Epiphany#10]
I used the golden contract thingie on tarnished greed to quickly make a shop pool in a random room (non special room) so that I can buy a bomb. I used Mr. ME!, the active item that steals shop items for you, and he did take the bomb but when I tried picking it up, it was turned into coins anyways. It shouldnt work like that because using Mr. ME!  is supposed to be equivelant of buying things for free. If this actually was working as you guys intended, then the item would be useless.

**Comment by OpenSauce04** [comment]
The team has decided that this is intended behaviour, and because of that this issue will not be fixed
