### ISSUE TITLE
Tarnished mangy unlock

### ISSUE THREAD

**Issue by 10293847560192837465** [OpenSauce04/Epiphany#14]
**Describe the bug**
When I use yum heart in the sac room, bleeding heart does not spawn. I have looked it up , but no one else seems to be having this problem.
---

**To Reproduce**
---
I did as the instructions said, (I looked up how to unlock her to see if I did something wrong), and never once got bleeding heart to spawn.
**Log**
---

**Screenshots**
---

**Version information:**
---
 - Installed wave number: 
 - Version number: 

**Additional context**
---

**Comment by Willytor** [comment]
i believe it only works if the sac room is on the first chapter (basement, cellar, etc.)

**Comment by 10293847560192837465** [comment]
Ok, I'll try that.
