### ISSUE TITLE
Game is not responding for 5 minutes every time i open it

### ISSUE THREAD

**Issue by Cooxie1** [OpenSauce04/Epiphany#16]
**Describe the bug**
i need to wait 5 minutes for the game to load because it isnt responding it 

**To Reproduce**
---

**Log**
---

**Screenshots**
---

**Version information:**
1.0
 - Installed wave number: 
 - Version number: 
wave 4
**Additional context**
---

**Comment by Cooxie1** [comment]
also when i go into the menu

**Comment by OpenSauce04** [comment]
I think I know what's happening here, can you run EpiphanyDiag and send me the produced file? I might be able to fix it for you

**Comment by OpenSauce04** [comment]
Duplicate of

**Comment by Kyedae69** [comment]
i have the exact same issue everytime i start the game with the mod installed my game doesnt respond but if i delete the mod it starts normaly

> I think I know what's happening here, can you run EpiphanyDiag and send me the produced file? I might be able to fix it for you

**Comment by AstralTM** [comment]
> I think I know what's happening here, can you run EpiphanyDiag and send me the produced file? I might be able to fix it for you

i have the same issue, here is my EpiphanyDiag

the game is normally functioning, but if i will put the epiphany file into the mods then the game won't open.

[EpiphanyDiagnostics.tar.gz](https://github.com/OpenSauce04/EpiphanyIssues/files/11511793/EpiphanyDiagnostics.tar.gz)
