### ISSUE TITLE
TR Isaac Blighted Dice + Dice Bag 

### ISSUE THREAD

**Issue by TwoWorldsApart** [OpenSauce04/Epiphany#18]
**Describe the bug**
--- 

Tarnished Isaac uses his blighted dice when you use a Dice from Dice Bag in a room. 

**To Reproduce**
--- 
1. Play as Tarnished Isaac
2. Get Dice Bag as a Trinket
3. If you enter a room and get a dice use it. 
4. You now have used your blighted dice without it being selected. 

**Log**
---

https://pastebin.com/RkpxBdc5 

**Version information:**
--- 
 - Installed wave number: 4
 - Version number: v4.5 

**Additional context**
---

It might also have to do with the amounts of cards you currently hold. In my pastebin I recreated it with 4 different Q items but it always used the BD when I used a dice from Dice Bag. It happened to me a few days ago in a full blown amazing run and it confused me so much. Had to test it again.

**Comment by OpenSauce04** [comment]
We can't fix this due to API issues, sorry!

**Comment by TwoWorldsApart** [comment]
Thats ok, thanks for clearing that up.
