### ISSUE TITLE
tarnished character menu door sends me into new game

### ISSUE THREAD

**Issue by syzzy** [OpenSauce04/Epiphany#21]
when i select the door it sends me into a new game where i spawn as a character with a black body and a question mark on its face 

![Untitled](https://user-images.githubusercontent.com/117120322/199103430-404c9793-383b-450b-9347-1e548ff6dc2d.png)

[EpiphanyDiagnostics.tar.gz](https://github.com/OpenSauce04/Epiphany/files/9904808/EpiphanyDiagnostics.tar.gz)

**Comment by OpenSauce04** [comment]
Please send your EpiphanyDiagnostics.tar.gz file. You can generate it using the EpiphanyDiag program in the mod's folder

**Comment by syzzy** [comment]
[EpiphanyDiagnostics.tar.gz](https://github.com/OpenSauce04/Epiphany/files/9911923/EpiphanyDiagnostics.tar.gz)

**Comment by OpenSauce04** [comment]
Your Isaac version is out of date. You are running v1.7.5, whereas the most recent version is v1.7.8a.
Please update your game, this should fix the issue
Additionally, your Epiphany installation is outdated. You have v4.6 installed, whereas the most recent version is v4.10
This isn't what's causing the problem, however you should stay updated when you can
