### ISSUE TITLE
Tarnished Maggy is unable to be unlocked for multiple reasons

### ISSUE THREAD

**Issue by ABirdNamedSuki** [OpenSauce04/Epiphany#28]
When I use Tainted Maggy's Yum Heart item in a self-sacrifice room, I am not rewarded with Bleeding Heart.

As a test, I gave her the Bleeding Heart item with console commands.
I then defeated regular path Mom and It Lives.

Just in case the unlock method required beating "actual Mom's heart",
I also went alt path and defeated harder Mom, opened the flesh wall, and defeated harder Mom's Heart

In neither scenario, did Tarnished Maggy become obtainable.

**Comment by ABirdNamedSuki** [comment]
If there is anything I can do to help confirm this bug, please let me know.

**Comment by OpenSauce04** [comment]
Please follow the issue format
