### ISSUE TITLE
TrMaggy keeps on bleeding if the Encyclopedia/Dead Sea Scrolls menu is on 

### ISSUE THREAD

**Issue by EGaroufalias** [OpenSauce04/Epiphany#7]

**Comment by NotSpooky54** [comment]
This is a "bug" from Dead Sea Scrolls, because if you open the dss while you have a familiar that moves freely, the familiar will still move.
So this is a problem from the side of dss devs.
And next time leave a desc because that part is **crucial**.
Sorry!

**Comment by EGaroufalias** [comment]
ah gotcha, sorry for not leaving further info!
