### ISSUE TITLE
Tarnished Maggie's new Health UI Doesn't appear as a COOP Player

### ISSUE THREAD

**Issue by jakenorris1124** [OpenSauce04/Epiphany#9]
**Describe the bug**
---
While playing as a COOP player, you cannot see TR Maggie's new health UI.

**To Reproduce**
---
Be player 2 and select TR Maggie (unknown if this also affects P3 and P4)

**Version information:**
---
 - Wave 4.2

**Comment by OpenSauce04** [comment]
Sorry it took so long to get around to looking at this properly, it will be fixed in the next patch
